POWERLEVEL9K_MODE="awesome-fontconfig"
source ~/.zsh-themes/powerlevel9k/powerlevel9k.zsh-theme

POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status rbenv rspec_stats)

# VCS color customization
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='042'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='101'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='104'

