[theme]
name = 'slick'
[theme.overrides]
separator = ' '

[icons]
name = 'awesome'
[icons.overrides]
music = '   '

[[block]]
block = 'music'
max_width = 21
marquee = false
player = 'spotify'
buttons = ['play', 'next']

[[block]]
block = 'cpu'
interval = 3

[[block]]
block = 'memory'
interval = 5
info_type = 'memory'
format_mem = '{Mup}%'
format_swap = '{SUp}%'

[[block]]
block = 'disk_space'
path = '/'
alias = '  '
info_type = 'available'
unit = 'GB'
interval = 20

[[block]]
block = 'time'
interval = 60
format = '%b %d %_I:%M %P'
